#!/usr/bin/env bash
# Generate the 4 separated Specmatic HTML reports (contract vs resiliency, per app spec)
# against the locally running app (port 5002) + LLM stub (port 9091).
set -u
REPO=/Volumes/BLACK_SHARK/MINOR_PROJECT
cd "$REPO"
APP_PORT=5001
SPECMATIC_JAR="${SPECMATIC_JAR:-$HOME/.specmatic/specmatic.jar}"
mkdir -p reports
# clear old text reports (Saachi: reports must be the HTML ones generated by Specmatic)
rm -f reports/*.txt

run() {  # name  spec  generative(true/empty)  extra_args
  local name="$1" spec="$2" gen="$3" extra="$4"
  echo "=================== $name ==================="
  rm -rf build/reports/specmatic
  local env=""
  [ "$gen" = "true" ] && env="SPECMATIC_GENERATIVE_TESTS=true"
  eval "$env java -jar \"$SPECMATIC_JAR\" test $spec $extra --host localhost --port $APP_PORT" > "/tmp/gen_$name.log" 2>&1
  local code=$?
  # pull the coverage + tests-run summary lines
  grep -E "API Coverage reported|Tests run:" "/tmp/gen_$name.log" | tail -3
  if [ -f build/reports/specmatic/test/html/index.html ]; then
    cp build/reports/specmatic/test/html/index.html "reports/$name.html"
    echo "  -> reports/$name.html  ($(du -h reports/$name.html | cut -f1))  [exit $code]"
  else
    echo "  !! no HTML report produced (exit $code)"; tail -5 "/tmp/gen_$name.log"
  fi
}

run "contract_public-contract"    contract_public.yaml ""     "--examples examples"
run "contract_public-resiliency"  contract_public.yaml true   "--examples examples"
run "api_contract-contract"       api_contract.yaml    ""     "--examples examples_api"
run "api_contract-resiliency"     api_contract.yaml    true   "--examples examples_api"

echo; echo "=== reports/ now ==="; ls -la reports/
